config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine, at:'/admin', as: 'rails_admin'
  devise_for :users
  root 'home#top'

  resources :shops do
    resources :comments
    post :confirm, on: :collection
  end
  resources :favorites, only: [:create, :destroy, :index]
  resources :rates, only: [:create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :shop
  belongs_to :user
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :rates, dependent: :destroy
  has_many :rate_users, through: :rates, source: :user
  validates :name, presence: true, length: { maximum: 50 }
  validates :impression, presence: true
  validates :payment, presence: true
  validates :station, presence:true
  mount_uploader :image, ImageUploader

  def self.search(search, pages)
    if search
      Shop.where(['station LIKE ?', "%#{search}%"]).page(pages)
    else
      Shop.all.page(pages)
    end
  end

  def self.search_category(search_category, shop_category, pages)
    if search_category == 'true'
      Shop.where(category: shop_category).page(pages)
    else
      Shop.all.page(pages)
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :shops, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_shops, through: :favorites, source: :shop
  has_many :rates, dependent: :destroy
  has_many :rate_shops, through: :rates, source: :shop
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:log_in, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @shop = Shop.find(params[:shop_id])
    @comment = @shop.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to shop_path(@shop), notice: '投稿できませんでした...' }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.js { render :index }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:shop_id,:content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(shop_id: params[:shop_id])
    @shop = params[:shop_id]
    redirect_to shop_url(@shop), notice: "#{favorite.shop.user.name}さんの記事をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to shops_url, notice: "#{favorite.shop.user.name}さんの記事をお気に入り解除しました"
  end

  def index
    @favorite_shops = current_user.favorite_shops
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  def create
    rate = current_user.rates.create(score: params[:rate][:score], shop_id: params[:rate][:shop_id])
    @shop = params[:rate][:shop_id]
     redirect_to shop_path(@shop), notice: "#{rate.shop.user.name}さんの投稿を評価しました"
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :index]
  PER = 5

  def index
    @shops = Shop.page(params[:page]).per(PER)

    # 並び替え
    if params[:low].present? || params[:low] == 'true'
      @shops = @shops.order(:payment).page(params[:page]).per(PER)
    elsif params[:high].present? || params[:high] == 'true'
      @shops = @shops.order(:payment).reverse_order.page(params[:page]).per(PER)
    else  
      @shops = Shop.page(params[:page]).per(PER)
    end

    #タイトル検索
    if params[:search].present?
      @shops = @shops.search(params[:search], params[:page]).per(PER)
    end

    #カテゴリー検索
    if params[:shop].present? && params[:shop][:search_category].present?
      @shops = @shops.search_category(params[:shop][:search_category], params[:shop][:category], params[:page]).per(PER)
    end

  end
  
  def new
    if params[:back]
      @shop = Shop.new(shop_params)
    else
      @shop = Shop.new
    end
  end

  def create
    @shop = current_user.shops.build(shop_params)
    
    if @shop.save
      redirect_to shops_path, notice: 'お店を登録しました！'
    else
      render 'new'
    end
  end

  def show       
    @shop = Shop.find(params[:id])
    @comments = @shop.comments
    @comment = @shop.comments.build
    @favorite = current_user.favorites.find_by(shop_id: @shop.id)
    @rate = current_user.rates.find_by(shop_id: @shop.id)
    # 評価の算出
    @sum = @shop.rates.sum(:score)
    @count = @shop.rates.count(:user_id)
    @average = (@sum/@count.to_f).round(2)
  end

  def edit
    if params[:test].present? || params[:test] == 'true'
      @shop = Shop.find(params[:id])
    else
      redirect_to shops_path
    end
  end

   def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shops_path, notice: 'お店の情報を編集しました！'
    else
      render 'edit'
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path, notice:'お店の情報を削除しました'
  end

  def confirm
    @shop = current_user.shops.build(shop_params)
    render :new if @shop.invalid?
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :category, :station, :phone_number, :adress, :payment, :impression, :image, :image_cache)
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_shops_path
    elsif action_name == 'edit'
      shop_path
    end
  end
end

app/views/comments/_form.html.erb
<%= form_with(model: [shop, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <br>
    <%= form.text_area :content %>
  </div>
  <p>！記入しなければボタンを押しても反映されません！</p>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <p><%= comment.content %></p>
        <p>投稿者：<%= comment.user.name %></p>
        <% if comment.user == current_user %>
          <p><%= link_to 'コメントを削除する', shop_comment_path(shop,comment), method: :delete, remote: true %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.shop.comments, shop: @comment.shop }) %>")
$("textarea").val('')

app/views/favorites/index.html.erb
<div class="wapper">
  <div class="container" >
    <h1>＊あなたの気になる一覧＊</h1>

    <table>
      <tr>
        <th>店名</th>
        <th>カテゴリー</th>
        <th>最寄駅</th>
        <th>予算</th>
      </tr>

      <% @favorite_shops.each do |shop| %>
        <tr>
          <td><%= shop.name %></td>
          <td><%= shop.category%></td>
          <td><%= shop.station %></td>
          <td><%= shop.payment %>円</td>
          <td><%= link_to '詳細', shop_path(shop.id) ,class: 'btn btn-default'%></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/home/top.html.erb
<div class="main top-main wapper">
  <div class="top-message">
    <h2>東京テイクアウト飯</h2>
    <br><br><br><br><br><br>
    <p>ようこそ！初めての方は左上の新規登録へ！登録済みの方はログインへ！ログインしたら一覧から！</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Takeout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wapper">
      <header>
        <ul>
          <% if user_signed_in? %>
            <li><a href="#"><%= link_to "＊お店一覧、投稿", shops_path %></a></li>
            <li><a href="#"><%= link_to '＊あなたの気になる一覧', favorites_path %></a></li>
            <li><a href="#"><%= link_to "＊ログアウト", destroy_user_session_path, method: :delete %></a></li>
          <% else %>
            <li><a href="#"><%= link_to "＊新規登録", new_user_registration_path %></a></li>
            <li><a href="#"><%= link_to "＊ログイン", new_user_session_path %></a></li>
          <% end %>

          <% if notice %>
            <p class="alert alert-notice"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-error"><%= alert %></p>
          <% end %>     
        </ul>  
      </header>
          <%= yield %>
      <footer>
      <br><br>
        Copyright © 2018 TokyoTakeOut INC All RIGHTS RESERVED.
      </footer> 
    </div>
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_with(model: @shop, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= @shop.errors.count %>件のエラーがあります。</h2>
      <ul>

        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
    <%= form.label :店名（必須） %>
    <%= form.text_field :name %>
  <br>
  <br>
    <%= form.label :ジャンル %>
    <%= form.select :category ,[['洋食','洋食'],['和食','和食'],['中華','中華'],['多国籍料理','多国籍料理'],['スイーツ','スイーツ'],['その他','その他']]%>
  <br>  
  <br>
  <%= form.label :最寄駅（必須）%>
  <%= form.text_field :station%>
  <br>
  <br>
  <%= form.label :電話番号 %>
  <%= form.text_field :phone_number%>
  <br>
  <br>
  <%= form.label :住所 %>
  <%= form.text_field :adress %>
  <br>
  <br>
  <%= form.label :予算（必須） %>
  <%= form.text_field :payment %>円
  <br>
  <br>
    <%= form.label :感想（必須） %>
    <%= form.text_area :impression %>
  <br>
  <br>
    <%= form.label :画像 %>
    <%= image_tag(@shop.image.url) if @shop.image.url %>
    <%= form.file_field :image %>
  <br>
  <br>  
  <%= form.submit %>
<% end %>
<br>
<%= link_to "ショップ一覧画面にもどる",shops_path %>

app/views/shops/confirm.html.erb
<div class="cyousei">
  <div class="wapper">
    <div class="container" >
      <h3>以下の内容で、送信する。</h3>

      <%= form_with(model: @shop, url: shops_path, local: true) do |form| %>
        <%= form.hidden_field :name %>
        <%= form.hidden_field :category %>
        <%= form.hidden_field :station %>
        <%= form.hidden_field :phone_number %>
        <%= form.hidden_field :adress %>
        <%= form.hidden_field :payment %>
        <%= form.hidden_field :impression %>
        <p>店名: <%= @shop.name %></p>
        <p>カテゴリー: <%= @shop.category %></p>
        <p>最寄駅: <%= @shop.station %></p>
        <p>電話番号: <%= @shop.phone_number %></p>
        <p>住所: <%= @shop.adress %>
        <p>お会計: <%= @shop.payment %>
        <p>感想: <%= @shop.impression %></p>
        <br><br><br>
        <%= form.submit  "登録する" %>
      <% end %>

      <%= form_with(model: @shop, url: new_shop_path, local: true, method: 'get') do |form| %>
        <%= form.hidden_field :name %>
        <%= form.hidden_field :category %>
        <%= form.hidden_field :station %>
        <%= form.hidden_field :phone_number %>
        <%= form.hidden_field :adress %>
        <%= form.hidden_field :payment %>
        <%= form.hidden_field :impression %>
        <%= form.hidden_field :image_cache %>
        <br><br><br>
        <%= form.submit "もどる", name: 'back' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shops/edit.html.erb
<div class="wapper">
  <div class="container" >
    <%= render 'form' %>
  </div>
</div>

app/views/shops/index.html.erb
<div class="wapper">
  <div class="container">
    <h1>＊みんなが投稿したShops＊</h1>

    <br><br>
    <%= form_with(model: Shop.new, local: true, method: :get, url: shops_path) do |f| %>
      <%= f.label :category, "カテゴリーで検索" %>
      <%= f.select :category,[['洋食','洋食'],['和食','和食'],['中華','中華'],['多国籍料理','多国籍料理'],['スイーツ','スイーツ'],['その他','その他']] %>
      <%= f.hidden_field :search_category, value: 'true'%>
      <%= f.submit "検索" %>
    <% end %>
    <br><br>
    <%= form_tag shops_path, :method => 'get' do %>
      <p>最寄駅で検索
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "検索", :name => nil %>
      </p>
    <% end %>
    <br>
    <%= link_to '予算の低い順に並び替え', shops_path(low: 'true') %>
    <%= link_to '予算の高い順に並び替え', shops_path(high: 'true') %>
    <br>

    <table>
      <tr>
        <th>店名</th>
        <th>カテゴリー</th>
        <th>最寄駅</th>
        <th>予算</th>
      </tr>

      <% @shops.each do |shop| %>
        <tr>
          <td>＊ <%= shop.name %></td>
          <td><%= shop.category%></td>
          <td><%= shop.station %></td>
          <td><%= shop.payment %>円</td>
          <td><%= link_to '詳細', shop_path(shop.id),class: 'btn btn-default' %></td>
          <% if shop.user == current_user %>
            <td><%= link_to '編集', edit_shop_path(shop.id,test: 'true'), class: 'btn btn-info' %></td>
            <td><%= link_to '削除', shop_path(shop.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger' %></td>
          <% end%>
        </tr>
      <% end %>
    </table>
    <br>
    <%= link_to '新しいお店を投稿する', new_shop_path,class: 'btn btn-default' %>
    <br>
    <%= paginate @shops %>
  </div>
</div>

app/views/shops/new.html.erb
<div class="cyousei">
  <div class="wapper">
    <div class="container" >
      <h2>ショップ情報を作成する</h2>
      <%= render 'form' %>
    </div> 
  </div>
</div>

app/views/shops/show.html.erb
<div class="cyousei">
  <div class="wapper">
    <div class="container" >
      <h1>ショップ詳細画面</h1>
      <br><br>
      <h4>＊店名: <%= @shop.name %><h4>
      <br>
      <p>＊カテゴリー: <%= @shop.category %></p>
      <br>
      <p>＊最寄駅: <%= @shop.station %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;＊電話番号: <%= @shop.phone_number %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;＊住所: <%= @shop.adress %></p>
      <br><br>
      <p>＊お会計: <%= @shop.payment %>円
      <br><br>
      <p>＊感想: <%= @shop.impression %></p>
      <% if @shop.image.present? %>
        <p>
        <strong>＊写真:</strong>
        <%= image_tag @shop.image.url,size:200 %>
        </p>
      <% end %>
      <br>
      <p>＊コメント一覧:</p>
      <div id="comments_area">
          <!-- 投稿されたコメント一覧をショップの詳細ページに表示するためのrender -->
        <%= render partial: 'comments/index', locals: { comments: @comments, shop: @shop } %>
      </div>

          <!-- コメント入力欄をショップの詳細ページに表示するためのrender -->
      <%= render partial: 'comments/form', locals: { comment: @comment, shop: @shop } %>
      <br>
      <% unless @shop.user_id == current_user.id %>
        <% if @rate.present? %>
          <br>
          <p>評価を終えています</p>
        <% else %>
          <br><br>
          <p>＊この投稿を評価する</p>
          <%= form_with(model: Rate, local: true, method: :post) do |f| %>
            <%= f.label :score, "5点満点で評価する" %>
            <%= f.select :score,[['1','1'],['2','2'],['3','3'],['4','4'],['5','5']] %>
            <%= f.hidden_field :shop_id, value: @shop.id %>
            <%= f.submit "評価" %>
          <% end %>
        <% end %>
          <br><br>
      <% end %>

      <p> ＊評価の平均（五段階）：<%= @average %></p>
      <p><progress max="5.00" value=<%= @average %>></p>
      <br><br>
      <% unless @shop.user_id == current_user.id %>
        <% if @favorite.present? %>
          <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'お気に入りする', favorites_path(shop_id: @shop.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>